name: Bug Report
description: Report a reproducible bug or unexpected behavior
labels: [bug]
body:
  - type: input
    id: title
    attributes:
      label: Summary
      placeholder: "Short description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "What did you do? What did you expect?"
      placeholder: |
        1. Run npm start
        2. Observe crash
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      render: shell
      placeholder: Paste any error messages here
    validations:
      required: false
